# Build stage
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npx expo export -p web

# Runtime stage
FROM nginx:alpine
# Copy the web build to Nginx's default serving directory
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
